# Generated by Django 3.2.5 on 2021-07-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description',
            field=models.CharField(default='jamshid', max_length=50),
            preserve_default=False,
        ),
    ]
